/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package avochoc.palindrome.SectionA;

import java.util.Scanner;

public class DataStructures1 
{
    

    public static void main(String[] args) 
    {

        Scanner scanner = new Scanner(System.in);
        System.out.print("Please type in your word or phrase to see if it is a palindrome: ");
        String Phrase = scanner.nextLine();

        // Remove spaces from the phrase
        String str = Phrase.replaceAll("\\s+", "");
        String reverseStr = "";

        int strLength = str.length();

        for (int i = (strLength - 1); i >= 0; --i) 
        {
            reverseStr = reverseStr + str.charAt(i);
        }
        
        // Remove spaces from the reversed phrase
        reverseStr = reverseStr.replaceAll("\\s+", "");

        if (str.equalsIgnoreCase(reverseStr)) 
        {
            System.out.println("Yes");
        } 
        else 
        {
            System.out.println("No");
        }
        scanner.close();
    }
}

